import Head from 'next/head';

export default function Home({ title = 'React avançado' }) {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>
        Welcome to tp <a href="https://nextjs.org">Next.js!</a>
      </h1>
      <h1>
        Welcome to tp <a href="https://nextjs.org">Next.js!</a>
      </h1>
    </div>
  );
}
